### ISSUE TITLE
Slick + Datasource instrumentation is broken in 7.9.0 with scala 2.13

### ISSUE THREAD

**Issue by smiklos** [newrelic/newrelic-java-agent#1000]
## Description

We are using Akka http 10.2.+ and Sangria so the only route we monitor is /graphql 

After upgrading to the current latest agent version (7.9.0) the agent seems to loose track of transactions across method calls. 
I can still manually create a transaction and link to it via its token but the transaction propagation between methods and future chaining no longer works at all.  I can only suspect the work related to https://github.com/newrelic/newrelic-java-agent/pull/876 as  cause

## Expected Behavior
When a web transaction starts we used to have segments span across the whole app, measuring db time and external calls. Now all of that is gone. Transactions still start but none of the above mentioned segments/metrics are measured anymore. 

## Your Environment
Tried both openjdk 11 and graalvm  22.1

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
@smiklos does the behavior you mention happen with `Akka HTTP` alone or is the combined use of `Sangria` necessary for the problem to occur? Any chance you have a simple app that can reproduce the problem?

While we can't commit to a date when we can investigate this further, having a small app that repros the problem is helpful!

**Comment by smiklos** [comment]
@kford-newrelic  I tried to reproduce this locally but it does work using akka http and sangria alone. 
However it seems that if I check out the latest main branch of the agent, remove code that was introduced by [this pr](https://github.com/newrelic/newrelic-java-agent/pull/876) ,, build it locally and it actually works totally fine. 

Somehow the changes in that pr nukes jdbc datasource (and maybe other) instrumentation. 
The pr was meant to fix an issue with scala 2.12 so curious how it affected us running on scala 2.13 but it certainly did

**Comment by smiklos** [comment]
I've ran the agent with debug and can see a bunch of instrumentation errors that happen during the transformation phase of scala final fields (as introduced by the pr I linked to) 

It shows that it is unable to transform several classes that are pretty important for a scala app to work with the agent : 

```
2022-11-10T14:44:42,665+0100 [25062 1] com.newrelic DEBUG: Instrumenting scala class scala/concurrent/impl/Promise$Transformation
2022-11-10T14:44:42,666+0100 [25062 1] com.newrelic FINE: Unable to transform class scala/concurrent/impl/Promise$Transformation
java.lang.TypeNotPresentException: Type scala/util/Try not present
	at com.newrelic.agent.deps.org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1041) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.Frame.merge(Frame.java:1299) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.Frame.merge(Frame.java:1244) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1611) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1547) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2665) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.instrumentation.custom.ScalaTraitFinalFieldTransformer.doTransform(ScalaTraitFinalFieldTransformer.java:40) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.instrumentation.custom.ScalaTraitFinalFieldTransformer.transform(ScalaTraitFinalFieldTransformer.java:20) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at com.newrelic.agent.instrumentation.context.InstrumentationClassTransformer.transform(InstrumentationClassTransformer.java:144) ~[newrelic.jar:7.12.0-SNAPSHOT]
	at java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244) ~[?:?]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) ~[?:?]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at scala.concurrent.impl.Promise$.<clinit>(Promise.scala:403) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.<init>(Promise.scala:113) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.concurrent.Promise$.apply(Promise.scala:126) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:411) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:390) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at scala.util.Try$.apply(Try.scala:210) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at scala.util.Success.flatMap(Try.scala:258) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:945) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:938) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:272) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:316) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:290) ~[com.typesafe.akka.akka-actor_2.13-2.6.20.jar:2.6.20]
	at io.theorg.service.Server$.delayedEndpoint$io$theorg$service$Server$1(Server.scala:114) ~[io.theorg.orgioservice-0.0.1.jar:0.0.1]
	at io.theorg.service.Server$delayedInit$body.apply(Server.scala:105) ~[io.theorg.orgioservice-0.0.1.jar:0.0.1]
	at scala.Function0.apply$mcV$sp(Function0.scala:39) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.Function0.apply$mcV$sp$(Function0.scala:39) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.App.$anonfun$main$1(App.scala:76) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.App.$anonfun$main$1$adapted(App.scala:76) ~[org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563) [org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561) [org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926) [org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.App.main(App.scala:76) [org.scala-lang.scala-library-2.13.8.jar:?]
	at scala.App.main$(App.scala:74) [org.scala-lang.scala-library-2.13.8.jar:?]
	at io.theorg.service.Server$.main(Server.scala:105) [io.theorg.orgioservice-0.0.1.jar:0.0.1]
	at io.theorg.service.Server.main(Server.scala) [io.theorg.orgioservice-0.0.1.jar:0.0.1]
Caused by: java.lang.ClassNotFoundException: scala.util.Try
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at com.newrelic.agent.deps.org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1039) ~[newrelic.jar:7.12.0-SNAPSHOT]
	... 59 more
```

**Comment by kford-newrelic** [comment]
Scala traits...sigh.

@smiklos thank you for this **excellent** analysis! We'll review this to see if we can easily build on your work for our next (Jan-Mar) quarter but we cannot commit that at the moment. Stay tuned.

In the meantime, are you able to continue using your own agent build as a workaround?

**Comment by smiklos** [comment]
@kford-newrelic  I guess we can use our own build but I was thinking that perhaps a quick fix where would be acceptable by you. 

If we marked `runnable` as `val runnable` in `slick.util.NewRelicRunnable` the final trait transformer would no longer pick up this class and instrumentation would work again for slick. If that's acceptable I'll make a pr

**Comment by kford-newrelic** [comment]
@smiklos yes a PR would be awesome - thank you!

**Comment by kford-newrelic** [comment]
#1103

**Comment by smiklos** [comment]
@kford-newrelic that was just a quick fix but the real problem has not been fixed, the one I outlined very detailed here. Other instrumentations libraries are probably also affected by this issue...
