### ISSUE TITLE
NullPointerException generated by setThreadTokenAndRefCount

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1149]
Customer was upgrading from the `7.5.0` agent to the `7.11.1` agent. The explicitly referenced use of `http4s 0.23` being a foundation of these apps, which encountered the following

```
at com.nr.agent.instrumentation.Utils.setThreadTokenAndRefCount(Utils.java:57)
java.lang.NullPointerException
at com.newrelic.agent.Transaction.linkTxOnThread(Transaction.java:1403)
at com.newrelic.agent.TokenImpl.link(TokenImpl.java:91)
at cats.effect.IOFiber.run(IOFiber.scala:21)
at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)
```

Need to review the referenced code and check whether a simple null check needs to be added or not.

**Comment by kford-newrelic** [comment]
May be addressed by #1148
