### ISSUE TITLE
new relic agent javax.net.ssl.SSLException: null

### ISSUE THREAD

**Issue by stanislavsokolovskyi** [newrelic/newrelic-java-agent#1439]
## Java new relic agent 8.4.0 fails to send data

Based on stack trace, `JDKPSSSigner.class` is loaded but it's not part of openjdk11. This class is part of application dependency bcprov-jdk14-138.jar(org.bouncycastle.jce.provider.JDKPSSSigner)

New relic agent works as expected when i exclude conflicting libraries in pom.xml:
```
<exclusions>
    <exclusion>
        <groupId>bouncycastle</groupId>
        <artifactId>bcprov-jdk14</artifactId>
    </exclusion>
    <exclusion>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk15on</artifactId>
    </exclusion>
</exclusions>
```

I reproduced tis problem also with other versions of java agent(7.0.1). 
I use default config from https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip

Stack trace
```
com.newrelic FINE: Unable to send events for regular transactions. Data for this harvest will be dropped.
javax.net.ssl.SSLException: null
    at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
    at com.newrelic.agent.deps.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.deps.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.apache.ApacheHttpClientWrapper.execute(ApacheHttpClientWrapper.java:162) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.connectAndSend(DataSenderImpl.java:590) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.send(DataSenderImpl.java:703) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.invoke(DataSenderImpl.java:531) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.invokeRunId(DataSenderImpl.java:521) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.sendAnalyticEventsForReservoir(DataSenderImpl.java:363) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.transport.DataSenderImpl.sendAnalyticsEvents(DataSenderImpl.java:330) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.RPMService.sendAnalyticsEventsSyncRestart(RPMService.java:505) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.RPMService.sendAnalyticsEvents(RPMService.java:485) ~[newrelic.jar:8.4.0]
    at com.newrelic.agent.service.analytics.TransactionEventsService.harvestEvents(TransactionEventsService.java:200) [newrelic.jar:8.4.0]
    at com.newrelic.agent.Harvestable.harvest(Harvestable.java:37) [newrelic.jar:8.4.0]
    at com.newrelic.agent.HarvestServiceImpl$HarvestableTracker$1.run(HarvestServiceImpl.java:506) [newrelic.jar:8.4.0]
    at com.newrelic.agent.util.SafeWrappers$1.run(SafeWrappers.java:34) [newrelic.jar:8.4.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
    at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
    at org.bouncycastle.crypto.signers.PSSSigner.<init>(Unknown Source) ~[?:?]
    at org.bouncycastle.crypto.signers.PSSSigner.<init>(Unknown Source) ~[?:?]
    at org.bouncycastle.jce.provider.JDKPSSSigner.engineInitVerify(Unknown Source) ~[?:?]
    at java.security.SignatureSpi.engineInitVerify(Unknown Source) ~[?:?]
    at java.security.Signature.initVerify(Unknown Source) ~[?:?]
    at java.security.Signature$1.initVerify(Unknown Source) ~[?:?]
    at sun.security.util.SignatureUtil.initVerifyWithParam(Unknown Source) ~[?:?]
    at sun.security.ssl.SignatureScheme.getVerifier(Unknown Source) ~[?:?]
    at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(Unknown Source) ~[?:?]
    at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeConsumer.consume(Unknown Source) ~[?:?]
    at sun.security.ssl.ServerKeyExchange$ServerKeyExchangeConsumer.consume(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:?]
    at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
    at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
    ... 32 more
```

## Steps to Reproduce

1. Build war app that includes external dependencies: bouncycastle:bcprov-jdk14, org.bouncycastle:bcprov-jdk15on
2. Build docker image based on: jetty:9.4.44-jre11
3. Deploy on Docker

[newrelic_agent.log](https://github.com/newrelic/newrelic-java-agent/files/12252121/newrelic_agent.log)

**Comment by jbedell-newrelic** [comment]
Hi @stanislavsokolovskyi, I'm trying to understand the use case for including conflicting dependencies like this.  Can you help?

**Comment by stanislavsokolovskyi** [comment]
we have updated dependencies, issue was resolved for us

**Comment by stanislavsokolovskyi** [comment]
we have updated dependencies, issue was resolved for us
