### ISSUE TITLE
wildfly and activemq instrumentation error

### ISSUE THREAD

**Issue by swanderson1** [newrelic/newrelic-java-agent#1699]
For the NewRelic java agent version 8.8.0 instrumenting wildfly:18.0.1.Final with activemq rar:5.16.7. Wildfly fails deploy the rar due to a classpath exception.

## Description
We are running wildfly:18.0.1.Final with activemq rar:5.16.7 inside a docker container. With the java agent version 8.5.0, the activemq rar deploys fine. With java agent version 8.8.0, we get the following stacktrace and the activemq rar fails to deploy.

```
java.lang.NoClassDefFoundError: Failed to link org/apache/activemq/management/StatsImpl (Module \"deployment.activemq-rar.rar\" from Service Module Loader): javax/management/j2ee/statistics/Stats
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:832)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.jca.validator.ValidateClass.<init>(ValidateClass.java:88)
	at org.jboss.jca.deployers.common.AbstractResourceAdapterDeployer.initAdminObject(AbstractResourceAdapterDeployer.java:858)
	at org.jboss.jca.deployers.common.AbstractResourceAdapterDeployer.createObjectsAndInjectValue(AbstractResourceAdapterDeployer.java:1931)
	at org.jboss.as.connector.services.resourceadapters.deployment.ResourceAdapterDeploymentService$WildFLyRaDeployer.doDeploy(ResourceAdapterDeploymentService.java:233)
	at org.jboss.as.connector.services.resourceadapters.deployment.ResourceAdapterDeploymentService.start(ResourceAdapterDeploymentService.java:126)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.lang.Thread.run(Thread.java:750)
```
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
activemq rar is deployed.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
The installation of NR daig into the container fails since sudo is missing.

## Steps to Reproduce
Run wildfly:18.0.1.Final with activemq.rar in the standalone/deployments directory. We have JAVA_OPTS in the environment as

```
-server -Xmx4G -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman
            -Djava.awt.headless=true -Duser.timezone=America/Chicago -Doracle.jdbc.timezoneAsRegion=false
            -javaagent:/opt/newrelic/newrelic.jar -XX:CompileCommand=exclude,net/sf/jasperreports/engine/export/JRGridLayout,horizontallyMergeEmptyCells
            -Dorg.apache.el.parser.COERCE_TO_ZERO=false
```

## Your Environment
docker container running debian:11.8
```
java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.392-b08, mixed mode)
```

**Comment by kford-newrelic** [comment]
@swanderson1 thank you for alerting us to this issue!

**Comment by jasonjkeller** [comment]
@swanderson1 Have you tried the fix detailed here? It applies to agent versions 8.7.0 and above.
https://docs.newrelic.com/docs/apm/agents/java-agent/troubleshooting/classloading-issues-from-jboss-and-wildfly/#solution-runtime

**Comment by kanderson250** [comment]
Reproed the issue and verified that the fix mentioned above (`-Dcom.newrelic.jboss.jsr77.fix=true`) works.

**Comment by swanderson1** [comment]
I ran test setup above using 8.9.1 of the agent which had the expected failure. I added `-Dcom.newrelic.jboss.jsr77.fix=true` which did resolve the issue. 

Thanks for the fix.
