### ISSUE TITLE
New Relic java agent 8.3.0 is Broken for Apache HttpClient5 v5.1.4

### ISSUE THREAD

**Issue by patrickjamesbarry** [newrelic/newrelic-java-agent#1715]
We are using 

- Apache Http Client 5.1.4 async api 
- org.apache.httpcomponents.core5 5.1.5

We pulled down your New Relic java agent 8.3.0 and immediately had issues. It is probably because you guys are embedding a newer version of the apache lib?  

Here is the output
2024-01-30T15:27:53,509-0500 [21064 84] com.newrelic FINER: Non-API call to setThrowable from asynchronous activity ignored: java.lang.ClassCastException: class org.apache.hc.core5.http.Message cannot be cast to class org.apache.hc.core5.http.message.BasicHttpResponse (org.apache.hc.core5.http.Message and org.apache.hc.core5.http.message.BasicHttpResponse are in unnamed module of loader 'app') with priority TRACER

Debugging, here is full stack trace
java.lang.ClassCastException: class org.apache.hc.core5.http.Message cannot be cast to class org.apache.hc.core5.http.message.BasicHttpResponse (org.apache.hc.core5.http.Message and org.apache.hc.core5.http.message.BasicHttpResponse are in unnamed module of loader 'app')
	at com.nr.agent.instrumentation.httpclient50.WrappedFutureCallback.completed(WrappedFutureCallback.java:36)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1$3$1.completed(InternalAbstractHttpAsyncClient.java:299)
	at org.apache.hc.core5.http.nio.support.BasicResponseConsumer$2.completed(BasicResponseConsumer.java:95)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:84)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:81)
	at org.apache.hc.core5.http.nio.support.BasicResponseConsumer.streamEnd(BasicResponseConsumer.java:127)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:235)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:280)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:335)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:551)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$400(SSLIOSession.java:72)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:172)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:133)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:85)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jasonjkeller** [comment]
Related: https://github.com/newrelic/newrelic-java-agent/issues/1649

**Comment by jbedell-newrelic** [comment]
Resolved by: https://github.com/newrelic/newrelic-java-agent/pull/1719

**Comment by patrickjamesbarry** [comment]
I see the gradle build for this module uses 5.2.1, and I related I am using 5.1.4.  Did you test using this older version of the lib before closing ticket?

dependencies {
    implementation(project(":agent-bridge"))
    implementation("org.apache.httpcomponents.client5:httpclient5:5.2.1")
}

jar {
    manifest { attributes 'Implementation-Title': 'com.newrelic.instrumentation.httpclient-5.0' }
}

verifyInstrumentation {
    passesOnly ('org.apache.httpcomponents.client5:httpclient5:[5.0,)')
    excludeRegex '.*alpha.*'
    excludeRegex '.*beta.*'
}
