### ISSUE TITLE
Remove redundant/unnecessary code from the dynamic attach branch

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#209]
The [dynamic attach prototype](https://github.com/newrelic/newrelic-java-agent/tree/dynamic-attach) has some code that is now redundant with the [LSI](https://github.com/newrelic/nri-introspector-java). We should remove any code from the agent that now lives in the LSI.

Additionally there is some code in the prototype that is unnecessary and should be removed, such as that for auto generating app names based on server type and other code for attaching to containers. Any logging specific to dynamic attach should be omitted if the agent is attached at startup. The StatusClient shouldn't be initialized if the agent is attached at startup and it probably shouldn't be in all dynamic attach scenarios but rather only when the LSI is being utilized.

Such code should also be removed. 

Let's aim to get the actual code necessary for dynamic attach down to the bare minimum.

**Comment by jasonjkeller** [comment]
When trying to attach using Java 11 (or any JDK > 8)

`java -jar newrelic.jar attach`

```
Run this command using a Java 8 JDK with tools.jar on the classpath
	java -cp /Users/jkeller/agents/newrelic_snapshot_build/newrelic.jar:${JAVA_HOME}/lib/tools.jar com.newrelic.bootstrap.BootstrapAgent attach
Error executing command
java.lang.RuntimeException: java.lang.ClassNotFoundException: sun.misc.VMSupport
	at com.newrelic.agent.discovery.SafeDiscovery.checkToolsJar(SafeDiscovery.java:29)
	at com.newrelic.agent.discovery.SafeDiscovery.discoverAndAttach(SafeDiscovery.java:14)
	at com.newrelic.agent.AgentCommandLineParser.parseCommand(AgentCommandLineParser.java:84)
	at com.newrelic.agent.Agent.main(Agent.java:304)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.newrelic.bootstrap.BootstrapAgent.main(BootstrapAgent.java:71)
Caused by: java.lang.ClassNotFoundException: sun.misc.VMSupport
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.newrelic.agent.discovery.SafeDiscovery.checkToolsJar(SafeDiscovery.java:22)
	... 8 more
```
