### ISSUE TITLE
Edge case when sending data to backend causes ConnectionPoolTimeoutException

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#24]
## Description
In rare cases it is possible for the agent to encounter a `ConnectionPoolTimeoutException` when a thread requests a connection to one of the backend agent endpoints. 

This happens because the connection pool is only [configured to have a single connection](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/transport/apache/ApacheHttpClientWrapper.java#L90) and the same [timeout value](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java#L171) is used for both the request to agent endpoints as well as the [request to the connection manager to get a connection from the pool](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/transport/apache/ApacheHttpClientWrapper.java#L106).

In the case where two threads make a request to the connection manager at the same time, one will successfully obtain the lone connection and the other will wait for the connection to become available again. For both threads a 120 second timeout will begin ticking down, for the the thread that has the connection to complete its request and for the thread waiting for a connection to obtain one from the pool. If the thread with the connection times out (`java.net.SocketTimeoutException`) the connection will be released back to the pool but the thread waiting for a connection will also have timed out (`com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException`).

Most HTTP requests aren't going to timeout over 120 seconds but in some cases it does happen.

## Expected Behavior
The connection pool and HTTP client used to make requests to agent endpoints should be more robustly configured so as to avoid `ConnectionPoolTimeoutException`s as described above.

## Troubleshooting

`java.net.SocketTimeoutException`:

```
2020-08-20T10:52:14,684-0700 [51325 33] com.newrelic INFO: Remote analytic_event_data call failed : java.net.SocketTimeoutException: Read timed out.
2020-08-20T10:52:14,687-0700 [51325 33] com.newrelic FINE: Unable to send events for regular transactions. Data for this harvest will be dropped.
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_265]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_265]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_265]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_265]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_265]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948) ~[?:1.8.0_265]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_265]
	at com.newrelic.agent.deps.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.apache.ApacheHttpClientWrapper.execute(ApacheHttpClientWrapper.java:155) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.connectAndSend(DataSenderImpl.java:559) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.send(DataSenderImpl.java:641) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.invoke(DataSenderImpl.java:500) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.invokeRunId(DataSenderImpl.java:490) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.sendAnalyticEventsForReservoir(DataSenderImpl.java:361) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.sendAnalyticsEvents(DataSenderImpl.java:333) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.RPMService.sendAnalyticsEventsSyncRestart(RPMService.java:500) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.RPMService.sendAnalyticsEvents(RPMService.java:481) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.service.analytics.TransactionEventsService.harvestEvents(TransactionEventsService.java:206) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.Harvestable.harvest(Harvestable.java:36) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl$HarvestableTracker$1.run(HarvestServiceImpl.java:464) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.util.SafeWrappers$1.run(SafeWrappers.java:34) [newrelic.jar:6.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

Followed by `com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException`:

```
2020-08-20T10:52:37,545-0700 [51325 32] com.newrelic INFO: Remote update_loaded_modules call failed : com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool.
2020-08-20T10:52:37,545-0700 [51325 32] com.newrelic FINE: Error sending JSON(update_loaded_modules): ["Jars",...]
2020-08-20T10:52:37,545-0700 [51325 32] com.newrelic FINEST: com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at com.newrelic.agent.deps.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:314) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:280) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.deps.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.apache.ApacheHttpClientWrapper.execute(ApacheHttpClientWrapper.java:155) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.connectAndSend(DataSenderImpl.java:559) ~[newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.send(DataSenderImpl.java:641) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.invoke(DataSenderImpl.java:500) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.invokeRunId(DataSenderImpl.java:490) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.transport.DataSenderImpl.sendModules(DataSenderImpl.java:421) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.RPMService.sendModulesSyncRestart(RPMService.java:469) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.RPMService.sendModules(RPMService.java:455) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.service.module.JarCollectorServiceImpl.beforeHarvest(JarCollectorServiceImpl.java:190) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl.notifyListenerBeforeHarvest(HarvestServiceImpl.java:424) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl.access$800(HarvestServiceImpl.java:36) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl$HarvestTask.doHarvest(HarvestServiceImpl.java:384) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl$HarvestTask.harvest(HarvestServiceImpl.java:356) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.HarvestServiceImpl$HarvestTask.run(HarvestServiceImpl.java:292) [newrelic.jar:6.0.0-SNAPSHOT]
	at com.newrelic.agent.util.SafeWrappers$1.run(SafeWrappers.java:34) [newrelic.jar:6.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

## Steps to Reproduce
I was able to repro this consistently by using a proxy between the agent and backend that would cause a `SocketTimeoutException` by delaying requests to one of the endpoints. Each time the subsequent request that was queued up would result in a `ConnectionPoolTimeoutException`.

## Your Environment
Java agent 6.0.0-SNAPSHOT (but should date back to when persistent connections were introduced)
apache-tomcat-9.0.31

## Additional context
Internal ticket: JAVA-6257

**Comment by jasonjkeller** [comment]
Resolved by #25
