### ISSUE TITLE
Weaving Postgresql JDBC connection/statement classes can cause PSQLExceptions to be logged

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#259]
It looks like `PSQLException`s are being caused by the agent getting unexpected values back from weaved Postgres connection/statement classes. These classes are likely adding a layer of indirection to the underlying JDBC classes that prevents the agent from getting the correct values. This was observed with the `jdbc-postgresql-9.4.1208` instrumentation but likely applies to other versions as well.

Postgres classes that were weaved:

```
com.newrelic.instrumentation.jdbc-generic/org/postgresql/jdbc/PgConnection
com.newrelic.instrumentation.jdbc-generic/org/postgresql/jdbc/PgPreparedStatement
com.newrelic.instrumentation.jdbc-generic/org/postgresql/jdbc/PgStatement
```

It has been confirmed that excluding these classes from being weaved by the agent prevents the `PSQLException`s:

```
  class_transformer:
    excludes: ^org/postgresql/jdbc/.*
```

The `PSQLException`s do not seem to impact the functionality of the application or Postgres queries however they do add a lot of noise to the agent and Postgres logs and are generally concerning. 

Agent logs:

```
2021-03-16T19:22:32,819-0400 [5059 180] com.newrelic FINER: Running explain: EXPLAIN (FORMAT JSON) select mp_id, tax_id, tax_code, mp_general_rating_sum, mp_number_of_general_ratings, last_order_time, vdr_id, vdr_name, vdr_addr_type, vdr_addr_line1, vdr_addr_line2, vdr_addr_line3, vdr_addr_line4, vdr_city, vdr_region_cd, vdr_region_name, vdr_postal_cd, cast(vdr_country_cd as text), vdr_country_name, vdr_general_rating_sum, vdr_number_of_general_ratings, commission, shipping_and_handling, free_shipping_threshold, vp_code, delisted_time, delisted_reason, heavy_shipping_threshold_qty, heavy_shipping_surcharge_each, fp_id, promised_handling_time, promised_ship_time, vp_average_ship_time, vendor_average_ship_time, oldest_sitting_time, license_required_sw, promo_name, store_front_appearance_order, promo_title, promo_descr, promo_addl_descr, vp_id, ver_id, pm_id, pp_price_eff_time, pp_min_qty, pp_min_qty_min, active_cd, pp_end_time, tz_id, days_of_week, days_of_month, months_of_year, cast(currency_cd as text), pp_prod_price, pp_prod_price_ver, pp_prod_price_corp, in_area_sw, has_license_sw, in_stock_sw, on_shelf_sw, creator, creation_time, updator, update_time from f_get_current_prices_pdp_by_mp_id_list(cast(? as int8[]), ?, ?, ?, ?, ?, ?, ?, ?)

2021-03-16T19:22:32,820-0400 [5059 180] com.newrelic FINER: explain plan error
org.postgresql.util.PSQLException: ERROR: function f_get_current_prices_pdp_by_mp_id_list(bigint[], bigint, character varying, boolean, boolean, character varying, boolean, character varying, character varying) does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Position: 1101
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[?:?]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[?:?]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[?:?]
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[?:?]
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[?:?]
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[?:?]
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106) ~[?:?]
at com.newrelic.agent.database.PreparedStatementExplainPlanExecutor.executeStatement(PreparedStatementExplainPlanExecutor.java:38) ~[newrelic.jar:6.4.2]
at com.newrelic.agent.database.DefaultExplainPlanExecutor.runExplainPlan(DefaultExplainPlanExecutor.java:67) [newrelic.jar:6.4.2]
at com.newrelic.agent.database.DatabaseService.runExplainPlan(DatabaseService.java:165) [newrelic.jar:6.4.2]
at com.newrelic.agent.database.DatabaseService.runExplainPlan(DatabaseService.java:157) [newrelic.jar:6.4.2]
at com.newrelic.agent.sql.SlowQueryInfo.asSqlTrace(SlowQueryInfo.java:137) [newrelic.jar:6.4.2]
at com.newrelic.agent.sql.SlowQueryAggregatorImpl.createSqlTraces(SlowQueryAggregatorImpl.java:70) [newrelic.jar:6.4.2]
at com.newrelic.agent.sql.SlowQueryAggregatorImpl.getAndClearSlowQueries(SlowQueryAggregatorImpl.java:50) [newrelic.jar:6.4.2]
at com.newrelic.agent.sql.SqlTraceServiceImpl.beforeHarvest(SqlTraceServiceImpl.java:95) [newrelic.jar:6.4.2]
at com.newrelic.agent.HarvestServiceImpl.notifyListenerBeforeHarvest(HarvestServiceImpl.java:424) [newrelic.jar:6.4.2]
at com.newrelic.agent.HarvestServiceImpl.access$800(HarvestServiceImpl.java:36) [newrelic.jar:6.4.2]
at com.newrelic.agent.HarvestServiceImpl$HarvestTask.doHarvest(HarvestServiceImpl.java:384) [newrelic.jar:6.4.2]
at com.newrelic.agent.HarvestServiceImpl$HarvestTask.harvest(HarvestServiceImpl.java:356) [newrelic.jar:6.4.2]
at com.newrelic.agent.HarvestServiceImpl$HarvestTask.run(HarvestServiceImpl.java:292) [newrelic.jar:6.4.2]
at com.newrelic.agent.util.SafeWrappers$1.run(SafeWrappers.java:34) [newrelic.jar:6.4.2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Postgres logs:
```
2021-03-05 19:20:33.506 EST:db=ruble:user=10.32.60.11(50342):process=8749 | ERROR: function f_get_current_prices_pdp_by_mp_id_list(bigint[], bigint, character varying, boolean, boolean, character varying, boolean, character varying, character varying) does not exist at character 1101

2021-03-05 19:20:33.506 EST:db=ruble:user=10.32.60.11(50342):process=8749 | HINT: No function matches the given name and argument types. You might need to add explicit type casts.

2021-03-05 19:20:33.506 EST:db=ruble:user=10.32.60.11(50342):process=8749 | STATEMENT: EXPLAIN (FORMAT JSON) select mp_id, tax_id, tax_code, mp_general_rating_sum, mp_number_of_general_ratings, last_order_time, vdr_id, vdr_name, vdr_addr_type, vdr_addr_line1, vdr_addr_line2, vdr_addr_line3, vdr_addr_line4, vdr_city, vdr_region_cd, vdr_region_name, vdr_postal_cd, cast(vdr_country_cd as text), vdr_country_name, vdr_general_rating_sum, vdr_number_of_general_ratings, commission, shipping_and_handling, free_shipping_threshold, vp_code, delisted_time, delisted_reason, heavy_shipping_threshold_qty, heavy_shipping_surcharge_each, fp_id, promised_handling_time, promised_ship_time, vp_average_ship_time, vendor_average_ship_time, oldest_sitting_time, license_required_sw, promo_name, store_front_appearance_order, promo_title, promo_descr, promo_addl_descr, vp_id, ver_id, pm_id, pp_price_eff_time, pp_min_qty, pp_min_qty_min, active_cd, pp_end_time, tz_id, days_of_week, days_of_month, months_of_year, cast(currency_cd as text), pp_prod_price, pp_prod_price_ver, pp_prod_price_corp, in_area_sw, has_license_sw, in_stock_sw, on_shelf_sw, creator, creation_time, updator, update_time from f_get_current_prices_pdp_by_mp_id_list(cast($1 as int8[]), $2, $3, $4, $5, $6, $7, $8, $9)
```

---

The `jdbc-generic` instrumentation weaves a `DefaultSqlTracer` into the class/method `org.postgresql.jdbc.PgStatement.executeQuery` which then calls `DefaultSqlTracer.setRawSql` to add the raw sql to the tracer. 

When the tracer is doing its finish work it creates an `ExplainPlanExecutor` that stores the raw sql captured from the `PgStatement`. 

The `DatabaseService` later invokes the `ExplainPlanExecutor` to run an explain plan if there are slow queries. The `ExplainPlanExecutor` converts the raw sql (unless the agent is configured with `record_sql: obfuscated/off`) into a JSON format and uses it to create a `PgStatement` (could be a `PgPreparedStatement` and looks to be in this case). The `PgStatement` and JSON sql are then used to try and execute the query and get the `ResultSet`, and this is where the `PSQLException` propagates back to in the agent code. 

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
Not selected for the next quarter's product roadmap. Will consider for a future quarter.

**Comment by kford-newrelic** [comment]
This does not appear to be a common occurrence. We will not be seeking to further investigate this issue.
