### ISSUE TITLE
java.lang.AbstractMethodError on Application Startup

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#365]
On every startup of the app, customer oberves below error in stdout: 

```
ERROR StatusLogger Caught java.lang.AbstractMethodError setting feature http://xml.org/sax/features/external-general-entities to false on DocumentBuilderFactory org.apache.xerces.jaxp.DocumentBuilderFactoryImpl@45820e51: java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V

java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V

        at com.newrelic.agent.deps.org.apache.logging.log4j.core.config.xml.XmlConfiguration.setFeature(XmlConfiguration.java:212)

        at com.newrelic.agent.deps.org.apache.logging.log4j.core.config.xml.XmlConfiguration.disableDtdProcessing(XmlConfiguration.java:205)

```
etc.

**Comment by kford-newrelic** [comment]
Since there does not appear to be an impact to agent functionality, this issue has not be chosen for the agent roadmap.
