### ISSUE TITLE
NPE on startup, crashing application

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#569]
Internal ticket https://newrelic.atlassian.net/browse/GTSE-12484

`2021-11-19T10:33:07,466-0800 [##### #] com.newrelic ERROR: Unable to start New Relic Agent. Please remove -javaagent from your startup arguments and contact New Relic support.
java.lang.NullPointerException: null
at com.newrelic.agent.config.Hostname.getAllInterfaceAddresses(Hostname.java:134) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.config.Hostname.discoverInUseIpAddress(Hostname.java:171) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.config.Hostname.getIpAddress(Hostname.java:161) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.utilization.UtilizationService.<init>(UtilizationService.java:92) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:197) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.service.AbstractService.start(AbstractService.java:63) ~[newrelic.jar:7.2.0]
at com.newrelic.agent.Agent.continuePremain(Agent.java:162) [newrelic.jar:7.2.0]...`

**Comment by twcrone** [comment]
newrelic-agent/src/main/java/com/newrelic/agent/config/Hostname.java#L128-L140
```
    // We want the value from InetAddress but it's more convenient to use InterfaceAddress
    private static List<InterfaceAddress> getAllInterfaceAddresses(String ip) {
        List<NetworkInterface> networkInterfaces = getNetworkInterfaces();
        for (NetworkInterface networkInterface : networkInterfaces) {
            List<InterfaceAddress> addresses = networkInterface.getInterfaceAddresses();
            for (InterfaceAddress address : addresses) {
                if (ip.equals(address.getAddress().getHostAddress())) {
                    return addresses;
                }
            }
        }
        return Collections.emptyList();
    }
```
