### ISSUE TITLE
Spring ApplicationEventPublisher.publishEvent() Throws Exception With Azul 17 and Java Agent

### ISSUE THREAD

**Issue by kibertoad** [newrelic/newrelic-java-agent#645]
## Description
When firing Spring events while using Azul Java 17 and NewRelic, this kind of errors is encountered:
```
java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [com.debex.broker.trading.TradeRouter$$EnhancerBySpringCGLIB$$ddf74fdb]
Method [public void com.debex.broker.trading.TradeRouter.routeOfferExecution(com.debex.broker.offer.model.ExecuteOfferEvent)]
Resolved arguments: 
[0] [type=com.debex.broker.offer.model.ExecuteOfferEvent] [value=com.debex.broker.offer.model.ExecuteOfferEvent[source=com.debex.broker.offer.OfferManager@678f4876]]

  at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:361)
  at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
  at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
  at com.debex.broker.offer.OfferManager.accept(OfferManager.java:215)
  at com.debex.broker.offer.OfferManager.accept(OfferManager.java:224)
  at com.debex.broker.offer.SimplexAccountOfferService.accept(SimplexAccountOfferService.java:184)
  at com.debex.broker.offer.SimplexAccountOfferService$$FastClassBySpringCGLIB$$444fde0.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
  at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
  at com.debex.broker.offer.SimplexApiOfferService$$EnhancerBySpringCGLIB$$f67a70ac.accept(<generated>)
  at com.debex.broker.paymentprovider.simplex.SimplexPaymentManager.executeAccept(SimplexPaymentManager.java:298)
  at com.debex.broker.paymentprovider.simplex.SimplexPaymentManager.handlePayment(SimplexPaymentManager.java:117)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
  at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
  at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
  a
```

It works fine on Azul Java 11 or without NewRelic instrumentation.

## Expected Behavior
Event publishing should work with Azul Java 17 and NewRelic instrumentation.

## Steps to Reproduce
Use Spring ApplicationEventPublisher.publishEvent() while running Azul Java 17 and NewRelic instrumentation.

## Your Environment
NewRelic 7.4.2, Azul Java 17.0.1, Spring Boot 2.5.7

(Migrate to Jira)

**Comment by meiao** [comment]
@kibertoad does the stack trace has any `Caused by` entries in it?
`UndeclaredThrowableException` is thrown when a checked exception goes thru a proxy and the exception is not amongst the ones thrown in the method declaration.
That exception could have clues to what is going on.

**Comment by kibertoad** [comment]
@meiao See attached stacktrace. BeanValidation is mentioned, and event in question has `@Valid` annotation on it. Nothing fancy, I think one NotNull field.

**Comment by meiao** [comment]
@kibertoad I saw the stack trace. But it is not complete.
Removing the agent prevents this from happening?

**Comment by kibertoad** [comment]
@meiao Yes.

**Comment by kibertoad** [comment]
@meiao Here is event that is failing:

```
public class EventThatFails extends ApplicationEvent {

    private static final long serialVersionUID = 5805843871464182572L;

    @Valid
    @NotNull
    private final Entry entry
```

```
public class Entry{

    @NotBlank
    private String id;

    @NotNull
    @Valid
    private Child child;

    @NotNull
    private BigDecimal val1;

    @NotNull
    private BigDecimal val2;

    private boolean isInternal;
```

```
public class Child {
    private static final String PATTERN1 = "\\w{2,12}";
    private static final String PATTERN2 = "\\W+";
    private static final String PAIR_PATTERN = PATTERN1 + PATTERN2 + PATTERN1 ;

    @NotBlank
    @Pattern(regexp = PATTERN1 )
    private final String left;

    @NotBlank
    @Pattern(regexp = PATTERN1 )
    private final String right;
```

**Comment by kford-newrelic** [comment]
Not selected for the next quarter's product roadmap. Will consider for a future quarter.
