### ISSUE TITLE
Jedis Instrumentation getting IndexOutOfBoundsException

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#773]
Some customers with Jedis instrumentation getting IndexOutOfBoundsException.

https://newrelic.atlassian.net/browse/GTSE-13781

https://newrelic.atlassian.net/browse/GTSE-13115

2022-01-21T10:09:05,858-0600 [1 54] com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINEST: An error was thrown from instrumentation library com.newrelic.instrumentation.jedis-3.0.0
java.lang.ArrayIndexOutOfBoundsException: 0
	at redis.clients.jedis.Connection.sendCommand(Connection.java:186) [jedis-3.6.3.jar!/:?]
	at redis.clients.jedis.Connection.sendCommand(Connection.java:158) [jedis-3.6.3.jar!/:?]
	at redis.clients.jedis.BinaryClient.ping(BinaryClient.java:186) [jedis-3.6.3.jar!/:?]
	at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:380) [jedis-3.6.3.jar!/:?]
	at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:214) [jedis-3.6.3.jar!/:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:810) [commons-pool2-2.9.0.jar!/:2.9.0]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1160) [commons-pool2-2.9.0.jar!/:2.9.0]
	at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:213) [commons-pool2-2.9.0.jar!/:2.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by kford-newrelic** [comment]
Not selected for next quarter's agent roadmap. Will consider for a future agent release.
