### ISSUE TITLE
Large max_samples_stored for application_logging throws ClassCastException

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#789]
If max_samples_stored set to something larger than Integer agent throws java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer and agent seems to shutdown gracefully and nothing is sent to NR1.

Probably do something less volatile and not shutdown agent.

**Comment by twcrone** [comment]
```
2022-03-18T10:25:00,687-0400 [13561 1] com.newrelic ERROR: Unable to start the New Relic Agent. Your application will continue to run but it will not be monitored.
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer
        at com.newrelic.agent.config.ApplicationLoggingForwardingConfig.<init>(ApplicationLoggingForwardingConfig.java:25) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.ApplicationLoggingConfigImpl.createApplicationLoggingForwardingConfig(ApplicationLoggingConfigImpl.java:62) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.ApplicationLoggingConfigImpl.<init>(ApplicationLoggingConfigImpl.java:47) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.ApplicationLoggingConfigImpl.createApplicationLoggingConfig(ApplicationLoggingConfigImpl.java:69) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.AgentConfigImpl.initApplicationLoggingConfig(AgentConfigImpl.java:744) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.AgentConfigImpl.<init>(AgentConfigImpl.java:357) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.AgentConfigImpl.createAgentConfig(AgentConfigImpl.java:283) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.config.ConfigServiceFactory.createConfigService(ConfigServiceFactory.java:38) ~[newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.Agent.tryToInitializeServiceManager(Agent.java:199) [newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.agent.Agent.continuePremain(Agent.java:140) [newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
        at com.newrelic.bootstrap.BootstrapAgent.startAgent(BootstrapAgent.java:193) [newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at com.newrelic.bootstrap.BootstrapAgent.premain(BootstrapAgent.java:130) [newrelic-agent-7.6.0-SNAPSHOT.jar:7.6.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386) [?:1.8.0_322]
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401) [?:1.8.0_322]
```

**Comment by twcrone** [comment]
In Base Config we *could* catch exceptions in this method and use the "defaultVal" parameter after logging there was an issue and we are using default.  For now, I'm going for a localized fix that we can broaden if we like.

```
    @Override
    public <T> T getProperty(String key, T defaultVal) {
        Object propVal = getProperties().get(key);
        if (propVal instanceof ServerProp) {
            propVal = ((ServerProp) propVal).getValue();
            return castValue(key, propVal, defaultVal);
        }
        Object override = getPropertyFromSystemEnvironment(key, defaultVal);
        if (override != null) {
            return castValue(key, override, defaultVal);
        }
        override = getPropertyFromSystemProperties(key, defaultVal);
        if (override != null) {
            return castValue(key, override, defaultVal);
        }
        return castValue(key, propVal, defaultVal);
    }

```

**Comment by twcrone** [comment]
Localized fix going into `ApplicationLoggingForwardingConfig` here:

```
    public ApplicationLoggingForwardingConfig(Map<String, Object> props, String parentRoot, boolean highSecurity) {
        super(props, parentRoot + ROOT + ".");
        maxSamplesStored = getProperty(MAX_SAMPLES_STORED, DEFAULT_MAX_SAMPLES_STORED);
        boolean storedMoreThan0 = maxSamplesStored > 0;
        enabled = storedMoreThan0 && !highSecurity && getProperty(ENABLED, DEFAULT_ENABLED);
    }
```
