### ISSUE TITLE
SSL Error while connecting to NR Collector

### ISSUE THREAD

**Issue by ClaudioWaldvogel** [newrelic/newrelic-java-agent#86]
[NOTE]: # NR Agent can not connect to NR Collector due to a **sun.security.provider.certpath.SunCertPathBuilderException**. Problem can be solved by providing an invalid ca_bundle_path property.

## Description
[NOTE]: # Agent(6.1.0) can not connect to NR Collector. It fails with an SunCertPathBuilderException. I verified it with a simple SpringBoot Application and tested it with JDK11 and JDK8. Since the Agent should be configured from ENV variables no configuration file is provided. NEW_RELIC_LICENSE_KEY and NEW_RELIC_APP_NAME are properly set and picked up by the Agent. Anyway, Agent can not connect to the Collector.
If NEW_RELIC_CA_BUNDLE_PATH=DOES_NOT_EXIST is provided, Agent is able to establish connection to the Collector.

Please find log files attached.

## Expected Behavior
[NOTE]: # Agent can connect to NR Collector without adding invalid NEW_RELIC_CA_BUNDLE_PATH path.

## 

## Steps to Reproduce
[NOTE]: # Attach agent to sample spring boot application and check the logs
**Does not work**
```bash
$ export NEW_RELIC_LICENSE_KEY=******
$ export NEW_RELIC_APP_NAME=DEMO
$ export NEW_RELIC_LOG_FILE_NAME=STDOUT
$ java -javaagent:newrelic.jar -jar target/demo-0.0.1-SNAPSHOT.jar
2020-10-16T09:19:50,332+0200 [82663 1] com.newrelic INFO: Configuration file not found. The agent will attempt to read required values from environment variables.
2020-10-16T09:19:50,361+0200 [82663 1] com.newrelic INFO: Using region aware collector host: collector.eu01.nr-data.net
2020-10-16T09:19:50,473+0200 [82663 1] com.newrelic INFO: Agent Host: ***** IP:*****
2020-10-16T09:19:50,473+0200 [82663 1] com.newrelic INFO: New Relic Agent v6.1.0 is initializing...
2020-10-16T09:19:51,324+0200 [82663 11] com.newrelic INFO: Instrumentation com.newrelic.instrumentation.jdbc-resultset is disabled. Skipping.
2020-10-16T09:19:53,182+0200 [82663 1] com.newrelic.agent.RPMServiceManagerImpl INFO: Configured to connect to New Relic at collector.eu01.nr-data.net:443
2020-10-16T09:19:53,945+0200 [82663 1] com.newrelic INFO: Setting audit_mode to false
2020-10-16T09:19:54,293+0200 [82663 1] com.newrelic INFO: New Relic Agent v6.1.0 has started
2020-10-16T09:19:54,293+0200 [82663 1] com.newrelic INFO: Agent class loader: com.newrelic.bootstrap.BootstrapAgent$JVMAgentClassLoader@2b71fc7e
2020-10-16T09:19:54,294+0200 [82663 1] com.newrelic INFO: Premain startup complete in 4,539ms

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
    '  |____| .__|_| |_|_| |_\__, | / / / /
  =========|_|==============|___/=/_/_/_/
  :: Spring Boot ::        (v2.3.4.RELEASE)

2020-10-16 09:19:56.078  INFO 82663 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication v0.0.1-SNAPSHOT on ***** with PID 82663 (*****/target/demo-0.0.1-SNAPSHOT.jar started by cwa in *****)
2020-10-16 09:19:56.083  INFO 82663 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2020-10-16 09:19:58.516  INFO 82663 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2020-10-16 09:19:59.293  INFO 82663 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2020-10-16T09:19:59,294+0200 [82663 31] com.newrelic INFO: Host name is *****, display host ***** for application DEMO
2020-10-16 09:19:59.319  INFO 82663 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 3.982 seconds (JVM running for 9.636)
2020-10-16T09:19:59,451+0200 [82663 31] com.newrelic INFO: Unable to connect to New Relic due to an SSL error. Consider enabling -Djavax.net.debug=all to debug your SSL configuration such as your trust store.
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_202-ea]
  at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[?:1.8.0_202-ea]
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[?:1.8.0_202-ea]
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[?:1.8.0_202-ea]
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[?:1.8.0_202-ea]
  at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[?:1.8.0_202-ea]
  at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[?:1.8.0_202-ea]
  at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[?:1.8.0_202-ea]
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[?:1.8.0_202-ea]
  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_202-ea]
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_202-ea]
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_202-ea]
  at com.newrelic.agent.deps.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.deps.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.apache.ApacheHttpClientWrapper.execute(ApacheHttpClientWrapper.java:162) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.connectAndSend(DataSenderImpl.java:552) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.send(DataSenderImpl.java:634) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.invoke(DataSenderImpl.java:493) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.invokeNoRunId(DataSenderImpl.java:488) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.parsePreconnectAndReturnHost(DataSenderImpl.java:208) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderImpl.connect(DataSenderImpl.java:186) [newrelic.jar:6.1.0]
  at com.newrelic.agent.RPMService.doConnect(RPMService.java:287) [newrelic.jar:6.1.0]
  at com.newrelic.agent.RPMService.launch(RPMService.java:247) [newrelic.jar:6.1.0]
  at com.newrelic.agent.rpm.RPMConnectionServiceImpl$RPMConnectionTask.attemptConnection(RPMConnectionServiceImpl.java:338) [newrelic.jar:6.1.0]
  at com.newrelic.agent.rpm.RPMConnectionServiceImpl$RPMConnectionTask.access$1100(RPMConnectionServiceImpl.java:105) [newrelic.jar:6.1.0]
  at com.newrelic.agent.rpm.RPMConnectionServiceImpl$RPMConnectionTask$3.run(RPMConnectionServiceImpl.java:240) [newrelic.jar:6.1.0]
  at com.newrelic.agent.util.SafeWrappers$1.run(SafeWrappers.java:34) [newrelic.jar:6.1.0]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202-ea]
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_202-ea]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_202-ea]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_202-ea]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202-ea]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202-ea]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202-ea]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[?:1.8.0_202-ea]
  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[?:1.8.0_202-ea]
  at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_202-ea]
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_202-ea]
  ... 38 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_202-ea]
  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_202-ea]
  at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_202-ea]
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[?:1.8.0_202-ea]
  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[?:1.8.0_202-ea]
  at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_202-ea]
  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_202-ea]
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_202-ea]
  ... 38 more
2020-10-16T09:19:59,512+0200 [82663 31] com.newrelic INFO: Remote preconnect call failed : javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
2020-10-16T09:19:59,512+0200 [82663 31] com.newrelic.agent.rpm.RPMConnectionServiceImpl INFO: Failed to connect to collector.eu01.nr-data.net:443 for DEMO: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
^C2020-10-16T09:20:00,946+0200 [82663 6] com.newrelic.agent.core.CoreServiceImpl INFO: JVM is shutting down
2020-10-16T09:20:00,959+0200 [82663 6] com.newrelic.agent.core.CoreServiceImpl INFO: New Relic Agent has shutdown
```

**Works**
```bash
$ export NEW_RELIC_LICENSE_KEY=******
$ export NEW_RELIC_APP_NAME=DEMO
$ export NEW_RELIC_LOG_FILE_NAME=STDOUT
$ export NEW_RELIC_CA_BUNDLE_PATH=DOES_NOT_EXIST
$ java -javaagent:newrelic.jar -jar target/demo-0.0.1-SNAPSHOT.jar
2020-10-16T09:23:06,024+0200 [82973 1] com.newrelic INFO: Configuration file not found. The agent will attempt to read required values from environment variables.
2020-10-16T09:23:06,052+0200 [82973 1] com.newrelic INFO: Using region aware collector host: collector.eu01.nr-data.net
2020-10-16T09:23:06,159+0200 [82973 1] com.newrelic INFO: Agent Host: ***** IP: *****
2020-10-16T09:23:06,159+0200 [82973 1] com.newrelic INFO: New Relic Agent v6.1.0 is initializing...
2020-10-16T09:23:07,015+0200 [82973 11] com.newrelic INFO: Instrumentation com.newrelic.instrumentation.jdbc-resultset is disabled. Skipping.
2020-10-16T09:23:08,798+0200 [82973 1] com.newrelic.agent.RPMServiceManagerImpl INFO: Configured to connect to New Relic at collector.eu01.nr-data.net:443
2020-10-16T09:23:08,881+0200 [82973 1] com.newrelic WARN: Unable to create SSL context
java.io.FileNotFoundException: DOES_NOT_EXIST (No such file or directory)
  at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_202-ea]
  at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_202-ea]
  at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_202-ea]
  at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_202-ea]
  at com.newrelic.agent.transport.apache.ApacheSSLManager.getKeyStore(ApacheSSLManager.java:110) ~[newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.apache.ApacheSSLManager.createSSLContext(ApacheSSLManager.java:41) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderFactory$DefaultDataSenderFactory.buildApacheHttpClientWrapper(DataSenderFactory.java:67) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderFactory$DefaultDataSenderFactory.create(DataSenderFactory.java:60) [newrelic.jar:6.1.0]
  at com.newrelic.agent.transport.DataSenderFactory.create(DataSenderFactory.java:46) [newrelic.jar:6.1.0]
  at com.newrelic.agent.RPMService.<init>(RPMService.java:107) [newrelic.jar:6.1.0]
  at com.newrelic.agent.RPMServiceManagerImpl.createRPMService(RPMServiceManagerImpl.java:174) [newrelic.jar:6.1.0]
  at com.newrelic.agent.RPMServiceManagerImpl.<init>(RPMServiceManagerImpl.java:78) [newrelic.jar:6.1.0]
  at com.newrelic.agent.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:237) [newrelic.jar:6.1.0]
  at com.newrelic.agent.service.AbstractService.start(AbstractService.java:63) [newrelic.jar:6.1.0]
  at com.newrelic.agent.Agent.continuePremain(Agent.java:157) [newrelic.jar:6.1.0]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202-ea]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202-ea]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202-ea]
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202-ea]
  at com.newrelic.bootstrap.BootstrapAgent.startAgent(BootstrapAgent.java:147) [newrelic.jar:6.1.0]
  at com.newrelic.bootstrap.BootstrapAgent.premain(BootstrapAgent.java:84) [newrelic.jar:6.1.0]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202-ea]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202-ea]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202-ea]
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202-ea]
  at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386) [?:1.8.0_202-ea]
  at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401) [?:1.8.0_202-ea]
2020-10-16T09:23:09,662+0200 [82973 1] com.newrelic INFO: Setting audit_mode to false
2020-10-16T09:23:09,985+0200 [82973 1] com.newrelic INFO: New Relic Agent v6.1.0 has started
2020-10-16T09:23:09,985+0200 [82973 1] com.newrelic INFO: Agent class loader: com.newrelic.bootstrap.BootstrapAgent$JVMAgentClassLoader@2b71fc7e
2020-10-16T09:23:09,985+0200 [82973 1] com.newrelic INFO: Premain startup complete in 4,524ms

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
    '  |____| .__|_| |_|_| |_\__, | / / / /
  =========|_|==============|___/=/_/_/_/
  :: Spring Boot ::        (v2.3.4.RELEASE)

2020-10-16 09:23:11.568  INFO 82973 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication v0.0.1-SNAPSHOT on ***** with PID 82973 (*****/target/demo-0.0.1-SNAPSHOT.jar started by cwa in *****)
2020-10-16 09:23:11.573  INFO 82973 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2020-10-16 09:23:13.733  INFO 82973 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2020-10-16 09:23:14.524  INFO 82973 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2020-10-16 09:23:14.542  INFO 82973 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 3.631 seconds (JVM running for 9.153)
2020-10-16T09:23:14,983+0200 [82973 31] com.newrelic INFO: Host name is *****, display host ***** for application DEMO
2020-10-16T09:23:15,215+0200 [82973 31] com.newrelic INFO: Collector redirection to collector-001.eu01.nr-data.net:443
2020-10-16T09:23:15,354+0200 [82973 31] com.newrelic INFO: Max payload size is 1,000,000 bytes
2020-10-16T09:23:15,354+0200 [82973 31] com.newrelic INFO: Agent run id: xxx
2020-10-16T09:23:15,355+0200 [82973 31] com.newrelic INFO: Agent 82973@*****/DEMO connected to collector.eu01.nr-data.net:443
2020-10-16T09:23:15,355+0200 [82973 31] com.newrelic INFO: Reporting to: https://rpm.eu.newrelic.com/accounts/****/applications/****
2020-10-16T09:23:15,356+0200 [82973 31] com.newrelic INFO: Using region aware collector host: collector.eu01.nr-data.neta
2020-10-16T09:23:15,360+0200 [82973 31] com.newrelic INFO: Using region aware collector host: collector.eu01.nr-data.net
2020-10-16T09:23:15,386+0200 [82973 31] com.newrelic INFO: Real user monitoring is enabled for application DEMO. Auto instrumentation is enabled.
```

```
## Your Environment 
- Agent Version: 6.1.0
- JVM 8 and 11

[newrelic_agent.sslerror.8.log](https://github.com/newrelic/newrelic-java-agent/files/5389816/newrelic_agent.sslerror.8.log)
[newrelic_agent.sslerror.11.log](https://github.com/newrelic/newrelic-java-agent/files/5389817/newrelic_agent.sslerror.11.log)
[newrelic_agent.working.8.log](https://github.com/newrelic/newrelic-java-agent/files/5389818/newrelic_agent.working.8.log)
[newrelic_agent.working.11.log](https://github.com/newrelic/newrelic-java-agent/files/5389819/newrelic_agent.working.11.log)

**Comment by jfsanchez-gh** [comment]
Same error here.. same work around.

**Comment by tspring** [comment]
Thanks for the issue. I suspect the problem is I had forgotten to add the certificates for the rpm.eu.newrelic.com. Could you try this branch and let us know if that resolves it? https://github.com/newrelic/newrelic-java-agent/pull/89
